// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectFlow.Infrastructure.Persistence;

#nullable disable

namespace ProjectFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261008022218_AddLabelNameUniqueIndex")]
    partial class AddLabelNameUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectFlow.Domain.Activity.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("old_value");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_logs");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_activity_logs_actor_id");

                    b.HasIndex("OrganizationId", "EntityId")
                        .HasDatabaseName("ix_activity_logs_organization_id_entity_id");

                    b.HasIndex("ProjectId", "OrganizationId")
                        .HasDatabaseName("ix_activity_logs_project_id_organization_id");

                    b.HasIndex("OrganizationId", "ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_activity_logs_organization_id_project_id_created_at");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("OrganizationId", "TaskId")
                        .HasDatabaseName("ix_comments_organization_id_task_id");

                    b.HasIndex("TaskId", "OrganizationId")
                        .HasDatabaseName("ix_comments_task_id_organization_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Epics.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_epics");

                    b.HasIndex("OrganizationId", "ProjectId")
                        .HasDatabaseName("ix_epics_organization_id_project_id");

                    b.HasIndex("ProjectId", "OrganizationId")
                        .HasDatabaseName("ix_epics_project_id_organization_id");

                    b.ToTable("epics", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Labels.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("OrganizationId", "ProjectId")
                        .HasDatabaseName("ix_labels_organization_id_project_id");

                    b.HasIndex("ProjectId", "OrganizationId")
                        .HasDatabaseName("ix_labels_project_id_organization_id");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Organizations.OrganizationMember", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_organization_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("NextTaskNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_task_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_projects_id_organization_id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_organization_id_key");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Sprints.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sprints");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_sprints_project_id_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("OrganizationId", "ProjectId")
                        .HasDatabaseName("ix_sprints_organization_id_project_id");

                    b.HasIndex("ProjectId", "OrganizationId")
                        .HasDatabaseName("ix_sprints_project_id_organization_id");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("integer")
                        .HasColumnName("story_points");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_tasks_id_organization_id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tasks_assignee_id");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("ix_tasks_epic_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_tasks_reporter_id");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_tasks_sprint_id");

                    b.HasIndex("OrganizationId", "AssigneeId")
                        .HasDatabaseName("ix_tasks_organization_id_assignee_id");

                    b.HasIndex("OrganizationId", "SprintId")
                        .HasDatabaseName("ix_tasks_organization_id_sprint_id");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tasks_project_id_number");

                    b.HasIndex("ProjectId", "OrganizationId")
                        .HasDatabaseName("ix_tasks_project_id_organization_id");

                    b.HasIndex("OrganizationId", "ProjectId", "Status")
                        .HasDatabaseName("ix_tasks_organization_id_project_id_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Tasks.TaskLabel", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.HasKey("TaskId", "LabelId")
                        .HasName("pk_task_labels");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_task_labels_label_id");

                    b.ToTable("task_labels", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjectFlow.Domain.Activity.ActivityLog", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_users_actor_id");

                    b.HasOne("ProjectFlow.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_logs_projects_project_id_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Comments.Comment", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("ProjectFlow.Domain.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_tasks_task_id_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Epics.Epic", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_epics_projects_project_id_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Labels.Label", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_labels_projects_project_id_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Organizations.OrganizationMember", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Organizations.Organization", null)
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");

                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_users_user_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Projects.Project", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organizations_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Sprints.Sprint", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sprints_projects_project_id_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tasks_users_assignee_id");

                    b.HasOne("ProjectFlow.Domain.Epics.Epic", null)
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_epics_epic_id");

                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_users_reporter_id");

                    b.HasOne("ProjectFlow.Domain.Sprints.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_sprints_sprint_id");

                    b.HasOne("ProjectFlow.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_projects_project_id_organization_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Tasks.TaskLabel", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Labels.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_labels_labels_label_id");

                    b.HasOne("ProjectFlow.Domain.Tasks.TaskItem", null)
                        .WithMany("Labels")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_labels_tasks_task_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("ProjectFlow.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Projects.Project", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ProjectFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
